name: Pack Mod
on:
  push:
    branches: [trunk]

  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Switch to the workspace
        run: cd ${{ github.workspace }}
      
      - name: Pack the mod
        run: zip more_backpacks.zip * */* */*/* -x *.sh *.xcf

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: more_backpacks
          path: ${{ github.workspace }}/more_backpacks.zip